environments:
  development:
  staging:
  production:
  
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

templates:
  default: &default
    chart: bitnami/{{`{{ .Release.Name }}`}}
    missingFileHandler: Warn
    values:
    - values/{{`{{ .Release.Name }}`}}/values.{{ .Environment.Name }}.yaml

releases:
  - name: prometheus
    <<: *default
    chart: bitnami/kube-{{`{{ .Release.Name }}`}}
    version: 8.14.1
    disableValidation: true

  - name: grafana
    <<: *default
    version: 8.4.6

  - name: grafana-settings
    chart: charts/{{`{{ .Release.Name }}`}}
    version: 0.1.0
