repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: prometheus
    chart: bitnami/kube-prometheus
    version: 6.6.3
    disableValidation: true
    values: 
    - values/prometheus/values.development.yaml

  - name: grafana
    chart: bitnami/grafana
    version: 7.6.4
    values: 
    - values/grafana/values.development.yaml

  - name: grafana-settings
    chart: charts/grafana-settings
    version: 0.1.0
