repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: prometheus
    chart: bitnami/kube-prometheus
    version: 8.14.1
    disableValidation: true
    values: 
    - values/prometheus/values.development.yaml

  - name: grafana
    chart: bitnami/grafana
    version: 8.4.6
    values: 
    - values/grafana/values.development.yaml

  - name: grafana-settings
    chart: charts/grafana-settings
    version: 0.1.0
